In [13]:
import  tensorflow as tf
from tensorflow import keras
from    tensorflow.keras import datasets, layers, optimizers, Sequential, metrics

In [14]:
x = tf.constant([2., 1., 0.1])
layer = layers.Softmax(axis=-1)
out = layer(x)
out

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.6590012, 0.242433 , 0.0985659], dtype=float32)>

In [15]:
out = tf.nn.softmax(x)
out

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.6590012, 0.242433 , 0.0985659], dtype=float32)>

In [19]:
network = Sequential([
    layers.Dense(3, activation=tf.nn.relu),
#     layers.ReLU(),
    layers.Dense(2, activation=tf.nn.relu),
#     layers.ReLU
])
x = tf.random.normal([4, 3])
out = network(x)
out

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[0.        , 0.        ],
       [0.22497952, 0.        ],
       [1.0739855 , 0.        ],
       [0.10878409, 0.        ]], dtype=float32)>

In [20]:
layers_num = 2
network = Sequential([])
for _ in range(layers_num):
    network.add(layers.Dense(3))
    network.add(layers.ReLU())
network.build(input_shape=(4,4))
network.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (4, 3)                    15        
_________________________________________________________________
re_lu_3 (ReLU)               (4, 3)                    0         
_________________________________________________________________
dense_13 (Dense)             (4, 3)                    12        
_________________________________________________________________
re_lu_4 (ReLU)               (4, 3)                    0         
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________
